# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 17:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=15, verbose_name='Code')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('img', models.ImageField(upload_to='site_media')),
                ('brand', models.CharField(db_index=True, max_length=15, verbose_name='Brand')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('colour', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BLUE', 'Bue'), ('BLACK', 'Black'), ('WHITE', 'White'), ('RED', 'Red'), ('PINK', 'Pink')], max_length=10, verbose_name='Colour'), default=list, size=None)),
                ('season', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('W', 'Winter'), ('S', 'Summer'), ('P', 'Spring'), ('A', 'Autumn')], max_length=4, verbose_name='Season'), default=list, size=None)),
                ('style', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SPORT', 'Sport'), ('ROCK', 'Rock'), ('BASIC', 'Basic'), ('CHIC', 'Chic')], max_length=10, verbose_name='Style'), default=list, size=None)),
                ('layer', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eigth'), (9, 'Nineth'), (10, 'Tenth')], verbose_name='Layer'), default=list, size=None)),
            ],
        ),
    ]
